"""Add core engine models

Revision ID: 987cb2dab6bd
Revises: d7e9c7f76de1
Create Date: 2026-07-02 06:58:42.940513+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Revision identifiers (used by Alembic) ────────────────────────────────
revision: str = "987cb2dab6bd"
down_revision: Union[str, None] = "d7e9c7f76de1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_test_experiments",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("target_metric", sa.String(length=50), nullable=False),
        sa.Column("variants", sa.JSON(), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("winning_variant", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "domain_health",
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("spf_valid", sa.Boolean(), nullable=False),
        sa.Column("dkim_valid", sa.Boolean(), nullable=False),
        sa.Column("dmarc_valid", sa.Boolean(), nullable=False),
        sa.Column("bounce_rate", sa.Float(), nullable=False),
        sa.Column("spam_complaint_rate", sa.Float(), nullable=False),
        sa.Column("reputation_score", sa.Integer(), nullable=False),
        sa.Column("last_checked_at", sa.DateTime(), nullable=True),
        sa.Column("is_blacklisted", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_domain_health_domain"), "domain_health", ["domain"], unique=True)
    op.create_table(
        "email_account_warmups",
        sa.Column("email_address", sa.String(length=255), nullable=False),
        sa.Column("is_warming_up", sa.Boolean(), nullable=False),
        sa.Column("warmup_day", sa.Integer(), nullable=False),
        sa.Column("current_daily_limit", sa.Integer(), nullable=False),
        sa.Column("max_daily_limit", sa.Integer(), nullable=False),
        sa.Column("emails_sent_today", sa.Integer(), nullable=False),
        sa.Column("last_sent_date", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_account_warmups_email_address"),
        "email_account_warmups",
        ["email_address"],
        unique=True,
    )
    op.create_table(
        "industry_memories",
        sa.Column("industry_name", sa.String(length=255), nullable=False),
        sa.Column("common_pain_points", sa.JSON(), nullable=False),
        sa.Column("buying_cycles", sa.JSON(), nullable=False),
        sa.Column("average_wait_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_industry_memories_industry_name"),
        "industry_memories",
        ["industry_name"],
        unique=True,
    )
    op.create_table(
        "market_memories",
        sa.Column("segment_name", sa.String(length=255), nullable=False),
        sa.Column("trends", sa.JSON(), nullable=False),
        sa.Column("competitor_landscape", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_memories_segment_name"), "market_memories", ["segment_name"], unique=True
    )
    op.create_table(
        "organization_memories",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("core_value_props", sa.JSON(), nullable=False),
        sa.Column("brand_voice_guidelines", sa.JSON(), nullable=False),
        sa.Column("global_do_not_contact", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_organization_memories_name"), "organization_memories", ["name"], unique=True
    )
    op.create_table(
        "conversation_memories",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("thread_history", sa.JSON(), nullable=False),
        sa.Column("current_intent", sa.String(length=50), nullable=True),
        sa.Column("next_action_due", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_conversation_memories_contact_id"),
        "conversation_memories",
        ["contact_id"],
        unique=True,
    )
    op.create_table(
        "outreach_sequences",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("current_step_index", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outreach_sequences_campaign_id"),
        "outreach_sequences",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outreach_sequences_contact_id"), "outreach_sequences", ["contact_id"], unique=False
    )
    op.create_table(
        "sequence_steps",
        sa.Column("sequence_id", sa.Uuid(), nullable=False),
        sa.Column("step_order", sa.Integer(), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("wait_days", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("scheduled_for", sa.DateTime(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["sequence_id"], ["outreach_sequences.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sequence_steps_scheduled_for"), "sequence_steps", ["scheduled_for"], unique=False
    )
    op.create_index(
        op.f("ix_sequence_steps_sequence_id"), "sequence_steps", ["sequence_id"], unique=False
    )
    op.alter_column(
        "research_profiles",
        "technologies_used",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "competitors",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "recent_news",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "ai_adoption_signals",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "why_now_score",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "opportunity_score",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "research_profiles",
        "opportunity_score",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "why_now_score",
        existing_type=sa.INTEGER(),
        server_default=sa.text("0"),
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "ai_adoption_signals",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "recent_news",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "competitors",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        existing_nullable=False,
    )
    op.alter_column(
        "research_profiles",
        "technologies_used",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        server_default=sa.text("'[]'::json"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_sequence_steps_sequence_id"), table_name="sequence_steps")
    op.drop_index(op.f("ix_sequence_steps_scheduled_for"), table_name="sequence_steps")
    op.drop_table("sequence_steps")
    op.drop_index(op.f("ix_outreach_sequences_contact_id"), table_name="outreach_sequences")
    op.drop_index(op.f("ix_outreach_sequences_campaign_id"), table_name="outreach_sequences")
    op.drop_table("outreach_sequences")
    op.drop_index(op.f("ix_conversation_memories_contact_id"), table_name="conversation_memories")
    op.drop_table("conversation_memories")
    op.drop_index(op.f("ix_organization_memories_name"), table_name="organization_memories")
    op.drop_table("organization_memories")
    op.drop_index(op.f("ix_market_memories_segment_name"), table_name="market_memories")
    op.drop_table("market_memories")
    op.drop_index(op.f("ix_industry_memories_industry_name"), table_name="industry_memories")
    op.drop_table("industry_memories")
    op.drop_index(
        op.f("ix_email_account_warmups_email_address"), table_name="email_account_warmups"
    )
    op.drop_table("email_account_warmups")
    op.drop_index(op.f("ix_domain_health_domain"), table_name="domain_health")
    op.drop_table("domain_health")
    op.drop_table("ab_test_experiments")
    # ### end Alembic commands ###
