"""add_prospecting_fields

Revision ID: 9894f6abeee1
Revises: 9468ad828849
Create Date: 2026-07-02 06:25:05.376964+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ── Revision identifiers (used by Alembic) ────────────────────────────────
revision: str = "9894f6abeee1"
down_revision: Union[str, None] = "9468ad828849"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("source_type", sa.String(length=100), nullable=True))
    op.add_column("contacts", sa.Column("retrieved_at", sa.DateTime(), nullable=True))
    op.add_column("contacts", sa.Column("verification_status", sa.String(length=50), nullable=True))
    op.add_column("contacts", sa.Column("mx_valid", sa.Boolean(), nullable=True))
    op.add_column("outreach_drafts", sa.Column("pain_signals", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outreach_drafts", "pain_signals")
    op.drop_column("contacts", "mx_valid")
    op.drop_column("contacts", "verification_status")
    op.drop_column("contacts", "retrieved_at")
    op.drop_column("contacts", "source_type")
    # ### end Alembic commands ###
