"""Add email tracking to OutreachDraft

Revision ID: 9468ad828849
Revises: 9a82900d4ab5
Create Date: 2026-07-02 05:55:38.791734+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ── Revision identifiers (used by Alembic) ────────────────────────────────
revision: str = "9468ad828849"
down_revision: Union[str, None] = "9a82900d4ab5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outreach_drafts", sa.Column("sent_at", sa.DateTime(), nullable=True))
    op.add_column("outreach_drafts", sa.Column("external_id", sa.String(length=255), nullable=True))
    op.add_column("outreach_drafts", sa.Column("thread_id", sa.String(length=255), nullable=True))
    op.create_index(
        op.f("ix_outreach_drafts_external_id"), "outreach_drafts", ["external_id"], unique=False
    )
    op.create_index(
        op.f("ix_outreach_drafts_thread_id"), "outreach_drafts", ["thread_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_outreach_drafts_thread_id"), table_name="outreach_drafts")
    op.drop_index(op.f("ix_outreach_drafts_external_id"), table_name="outreach_drafts")
    op.drop_column("outreach_drafts", "thread_id")
    op.drop_column("outreach_drafts", "external_id")
    op.drop_column("outreach_drafts", "sent_at")
    # ### end Alembic commands ###
