"""Add intelligence and memory models

Revision ID: d7e9c7f76de1
Revises: 9894f6abeee1
Create Date: 2026-07-02 06:40:19.466116+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ── Revision identifiers (used by Alembic) ────────────────────────────────
revision: str = "d7e9c7f76de1"
down_revision: Union[str, None] = "9894f6abeee1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaign_memories",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("successful_angles", sa.JSON(), nullable=False),
        sa.Column("failed_angles", sa.JSON(), nullable=False),
        sa.Column("audience_insights", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_memories_campaign_id"), "campaign_memories", ["campaign_id"], unique=True
    )
    op.create_table(
        "company_memories",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("known_objections", sa.JSON(), nullable=False),
        sa.Column("past_engagement_signals", sa.JSON(), nullable=False),
        sa.Column("buying_intent_score", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_company_memories_company_id"), "company_memories", ["company_id"], unique=True
    )
    op.create_table(
        "contact_memories",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("communication_preferences", sa.JSON(), nullable=False),
        sa.Column("past_replies", sa.JSON(), nullable=False),
        sa.Column("sentiment", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contact_memories_contact_id"), "contact_memories", ["contact_id"], unique=True
    )
    op.add_column("outreach_drafts", sa.Column("reply_status", sa.String(length=50), nullable=True))
    op.add_column("outreach_drafts", sa.Column("reply_received_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_outreach_drafts_reply_status"), "outreach_drafts", ["reply_status"], unique=False
    )
    op.add_column("research_profiles", sa.Column("employees", sa.Integer(), nullable=True))
    op.add_column("research_profiles", sa.Column("revenue_estimated", sa.Text(), nullable=True))
    op.add_column("research_profiles", sa.Column("funding", sa.JSON(), nullable=True))
    op.add_column("research_profiles", sa.Column("technologies_used", sa.JSON(), server_default='[]', nullable=False))
    op.add_column("research_profiles", sa.Column("competitors", sa.JSON(), server_default='[]', nullable=False))
    op.add_column("research_profiles", sa.Column("hr_maturity", sa.Text(), nullable=True))
    op.add_column("research_profiles", sa.Column("recent_news", sa.JSON(), server_default='[]', nullable=False))
    op.add_column("research_profiles", sa.Column("ai_adoption_signals", sa.JSON(), server_default='[]', nullable=False))
    op.add_column("research_profiles", sa.Column("why_now_score", sa.Integer(), server_default='0', nullable=False))
    op.add_column("research_profiles", sa.Column("opportunity_score", sa.Integer(), server_default='0', nullable=False))
    op.drop_column("research_profiles", "outreach_angles")
    op.drop_column("research_profiles", "recommended_pitch")
    op.drop_column("research_profiles", "why_now")
    op.drop_column("research_profiles", "summary")
    op.drop_column("research_profiles", "next_recommended_action")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "research_profiles",
        sa.Column("next_recommended_action", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "research_profiles", sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "research_profiles", sa.Column("why_now", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "research_profiles",
        sa.Column("recommended_pitch", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "research_profiles",
        sa.Column(
            "outreach_angles",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("research_profiles", "opportunity_score")
    op.drop_column("research_profiles", "why_now_score")
    op.drop_column("research_profiles", "ai_adoption_signals")
    op.drop_column("research_profiles", "recent_news")
    op.drop_column("research_profiles", "hr_maturity")
    op.drop_column("research_profiles", "competitors")
    op.drop_column("research_profiles", "technologies_used")
    op.drop_column("research_profiles", "funding")
    op.drop_column("research_profiles", "revenue_estimated")
    op.drop_column("research_profiles", "employees")
    op.drop_index(op.f("ix_outreach_drafts_reply_status"), table_name="outreach_drafts")
    op.drop_column("outreach_drafts", "reply_received_at")
    op.drop_column("outreach_drafts", "reply_status")
    op.drop_index(op.f("ix_contact_memories_contact_id"), table_name="contact_memories")
    op.drop_table("contact_memories")
    op.drop_index(op.f("ix_company_memories_company_id"), table_name="company_memories")
    op.drop_table("company_memories")
    op.drop_index(op.f("ix_campaign_memories_campaign_id"), table_name="campaign_memories")
    op.drop_table("campaign_memories")
    # ### end Alembic commands ###
