"""rename_kultrp_to_product

Revision ID: 1d5b6784b74f
Revises: 987cb2dab6bd
Create Date: 2026-07-15 16:42:04.894476+00:00
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# ── Revision identifiers (used by Alembic) ────────────────────────────────
revision: str = "1d5b6784b74f"
down_revision: Union[str, None] = "987cb2dab6bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provider_events",
        sa.Column("provider_name", sa.String(length=50), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("received_at", sa.DateTime(), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_provider_events_processed"), "provider_events", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_provider_events_provider_name"), "provider_events", ["provider_name"], unique=False
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_date", sa.DateTime(), nullable=False),
        sa.Column("metric_name", sa.String(length=50), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_analytics_snapshots_campaign_id"),
        "analytics_snapshots",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analytics_snapshots_snapshot_date"),
        "analytics_snapshots",
        ["snapshot_date"],
        unique=False,
    )
    op.create_table(
        "campaign_metrics",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("total_sent", sa.Integer(), nullable=False),
        sa.Column("total_delivered", sa.Integer(), nullable=False),
        sa.Column("total_bounced", sa.Integer(), nullable=False),
        sa.Column("total_deferred", sa.Integer(), nullable=False),
        sa.Column("total_opened", sa.Integer(), nullable=False),
        sa.Column("total_clicked", sa.Integer(), nullable=False),
        sa.Column("total_replied", sa.Integer(), nullable=False),
        sa.Column("total_meetings_booked", sa.Integer(), nullable=False),
        sa.Column("total_unsubscribed", sa.Integer(), nullable=False),
        sa.Column("total_spam_complaints", sa.Integer(), nullable=False),
        sa.Column("health_score", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_metrics_campaign_id"), "campaign_metrics", ["campaign_id"], unique=True
    )
    op.create_table(
        "campaign_runs",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_drafts", sa.Integer(), nullable=False),
        sa.Column("successful_deliveries", sa.Integer(), nullable=False),
        sa.Column("failed_deliveries", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_runs_campaign_id"), "campaign_runs", ["campaign_id"], unique=False
    )
    op.create_table(
        "campaign_states",
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("transitioned_at", sa.DateTime(), nullable=False),
        sa.Column("transition_history", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_states_campaign_id"), "campaign_states", ["campaign_id"], unique=True
    )
    op.create_index(op.f("ix_campaign_states_state"), "campaign_states", ["state"], unique=False)
    op.create_table(
        "event_audits",
        sa.Column("event_hash", sa.String(length=255), nullable=False),
        sa.Column("processed_at", sa.DateTime(), nullable=False),
        sa.Column("provider_event_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["provider_event_id"], ["provider_events.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_event_audits_event_hash"), "event_audits", ["event_hash"], unique=True)
    op.create_table(
        "sales_intelligence_profiles",
        sa.Column("company_id", sa.Uuid(), nullable=False),
        sa.Column("executive_summary", sa.Text(), nullable=True),
        sa.Column("business_overview", sa.Text(), nullable=True),
        sa.Column("business_model", sa.Text(), nullable=True),
        sa.Column("target_customers", sa.Text(), nullable=True),
        sa.Column("products_services", sa.Text(), nullable=True),
        sa.Column("growth_stage", sa.Text(), nullable=True),
        sa.Column("strategic_initiatives", sa.Text(), nullable=True),
        sa.Column("competitive_landscape", sa.Text(), nullable=True),
        sa.Column("key_differentiators", sa.Text(), nullable=True),
        sa.Column("recent_news", sa.JSON(), nullable=False),
        sa.Column("recent_funding", sa.JSON(), nullable=True),
        sa.Column("technology_stack", sa.JSON(), nullable=False),
        sa.Column("hiring_activity", sa.Text(), nullable=True),
        sa.Column("hiring_signals", sa.JSON(), nullable=False),
        sa.Column("buying_signals", sa.JSON(), nullable=False),
        sa.Column("digital_transformation_signals", sa.JSON(), nullable=False),
        sa.Column("pain_points", sa.JSON(), nullable=False),
        sa.Column("product_value_mapping", sa.JSON(), nullable=False),
        sa.Column("potential_decision_makers", sa.JSON(), nullable=False),
        sa.Column("communication_style", sa.Text(), nullable=True),
        sa.Column("risk_assessment", sa.Text(), nullable=True),
        sa.Column("sales_opportunity_summary", sa.Text(), nullable=True),
        sa.Column("outreach_intelligence", sa.JSON(), nullable=False),
        sa.Column("confidence_score", sa.Integer(), nullable=False),
        sa.Column("supporting_sources", sa.JSON(), nullable=False),
        sa.Column(
            "last_verified_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sales_intelligence_profiles_company_id"),
        "sales_intelligence_profiles",
        ["company_id"],
        unique=True,
    )
    op.create_table(
        "recipient_activities",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("first_opened_at", sa.DateTime(), nullable=True),
        sa.Column("last_opened_at", sa.DateTime(), nullable=True),
        sa.Column("open_count", sa.Integer(), nullable=False),
        sa.Column("first_clicked_at", sa.DateTime(), nullable=True),
        sa.Column("last_clicked_at", sa.DateTime(), nullable=True),
        sa.Column("click_count", sa.Integer(), nullable=False),
        sa.Column("replied_at", sa.DateTime(), nullable=True),
        sa.Column("bounced_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipient_activities_campaign_id"),
        "recipient_activities",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_activities_contact_id"),
        "recipient_activities",
        ["contact_id"],
        unique=False,
    )
    op.create_table(
        "recipient_lifecycles",
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("state_entered_at", sa.DateTime(), nullable=False),
        sa.Column("next_evaluation_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recipient_lifecycles_campaign_id"),
        "recipient_lifecycles",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_lifecycles_contact_id"),
        "recipient_lifecycles",
        ["contact_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_lifecycles_next_evaluation_at"),
        "recipient_lifecycles",
        ["next_evaluation_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipient_lifecycles_state"), "recipient_lifecycles", ["state"], unique=False
    )
    op.create_table(
        "campaign_deliveries",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("draft_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("provider_name", sa.String(length=50), nullable=True),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["draft_id"], ["outreach_drafts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["campaign_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_campaign_deliveries_draft_id"), "campaign_deliveries", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_deliveries_provider_message_id"),
        "campaign_deliveries",
        ["provider_message_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_deliveries_run_id"), "campaign_deliveries", ["run_id"], unique=False
    )
    op.create_table(
        "decision_history",
        sa.Column("recipient_lifecycle_id", sa.Uuid(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("decision", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("reason", sa.String(length=1000), nullable=False),
        sa.Column("execution_status", sa.String(length=50), nullable=False),
        sa.Column("execution_outcome", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("llm_version", sa.String(length=100), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("rule_version", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_lifecycle_id"], ["recipient_lifecycles.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_decision_history_execution_status"),
        "decision_history",
        ["execution_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_decision_history_recipient_lifecycle_id"),
        "decision_history",
        ["recipient_lifecycle_id"],
        unique=False,
    )
    op.create_table(
        "delivery_attempts",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["delivery_id"], ["campaign_deliveries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_attempts_delivery_id"), "delivery_attempts", ["delivery_id"], unique=False
    )
    op.create_table(
        "delivery_events",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["delivery_id"], ["campaign_deliveries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_delivery_events_delivery_id"), "delivery_events", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_delivery_events_event_type"), "delivery_events", ["event_type"], unique=False
    )
    op.create_table(
        "email_events",
        sa.Column("delivery_id", sa.Uuid(), nullable=False),
        sa.Column("campaign_id", sa.Uuid(), nullable=False),
        sa.Column("contact_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("provider_name", sa.String(length=50), nullable=False),
        sa.Column("provider_message_id", sa.String(length=255), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["contact_id"], ["contacts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["delivery_id"], ["campaign_deliveries.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_email_events_campaign_id"), "email_events", ["campaign_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_events_contact_id"), "email_events", ["contact_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_events_delivery_id"), "email_events", ["delivery_id"], unique=False
    )
    op.create_index(
        op.f("ix_email_events_event_type"), "email_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_email_events_occurred_at"), "email_events", ["occurred_at"], unique=False
    )
    op.create_index(
        op.f("ix_email_events_provider_message_id"),
        "email_events",
        ["provider_message_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_research_profiles_company_id"), table_name="research_profiles")
    op.drop_table("research_profiles")
    op.alter_column(
        "ab_test_experiments",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "ab_test_experiments",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "campaign_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "campaign_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "campaigns",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "campaigns",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("companies", sa.Column("enrichment_data", sa.JSON(), nullable=True))
    op.alter_column(
        "companies",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "company_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "company_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "contact_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "contact_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column("contacts", sa.Column("enrichment_data", sa.JSON(), nullable=True))
    op.alter_column(
        "contacts",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "contacts",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "domain_health",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "domain_health",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "email_account_warmups",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "email_account_warmups",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "industry_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "industry_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "market_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "market_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "organization_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "organization_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.add_column(
        "outreach_drafts", sa.Column("approval_status", sa.String(length=50), nullable=False)
    )
    op.add_column("outreach_drafts", sa.Column("qa_score", sa.Integer(), nullable=True))
    op.add_column("outreach_drafts", sa.Column("qa_report", sa.JSON(), nullable=True))
    op.add_column("outreach_drafts", sa.Column("operator_notes", sa.Text(), nullable=True))
    op.alter_column(
        "outreach_drafts",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_drafts",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_sequences",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_sequences",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sequence_steps",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "sequence_steps",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes for this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "sequence_steps",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "sequence_steps",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_sequences",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_sequences",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_drafts",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "outreach_drafts",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.drop_column("outreach_drafts", "operator_notes")
    op.drop_column("outreach_drafts", "qa_report")
    op.drop_column("outreach_drafts", "qa_score")
    op.drop_column("outreach_drafts", "approval_status")
    op.alter_column(
        "organization_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "organization_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "market_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "market_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "industry_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "industry_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "email_account_warmups",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "email_account_warmups",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "domain_health",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "domain_health",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "conversation_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "contacts",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "contacts",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.drop_column("contacts", "enrichment_data")
    op.alter_column(
        "contact_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "contact_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "company_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "company_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.drop_column("companies", "enrichment_data")
    op.alter_column(
        "campaigns",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "campaigns",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "campaign_memories",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "campaign_memories",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "ab_test_experiments",
        "updated_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.alter_column(
        "ab_test_experiments",
        "created_at",
        existing_type=sa.DATETIME(),
        server_default=sa.text("(now())"),
        existing_nullable=False,
    )
    op.create_table(
        "research_profiles",
        sa.Column("company_id", sa.CHAR(length=32), nullable=False),
        sa.Column("hiring_signals", sqlite.JSON(), nullable=False),
        sa.Column("growth_indicators", sqlite.JSON(), nullable=False),
        sa.Column("public_pain_points", sqlite.JSON(), nullable=False),
        sa.Column("best_contact", sqlite.JSON(), nullable=True),
        sa.Column("raw_evidence", sqlite.JSON(), nullable=False),
        sa.Column("llm_confidence", sa.INTEGER(), nullable=False),
        sa.Column("data_quality", sa.INTEGER(), nullable=False),
        sa.Column("freshness_score", sa.INTEGER(), nullable=False),
        sa.Column(
            "last_verified_at", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False
        ),
        sa.Column("id", sa.CHAR(length=32), nullable=False),
        sa.Column("created_at", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), server_default=sa.text("(now())"), nullable=False),
        sa.Column("employees", sa.INTEGER(), nullable=True),
        sa.Column("revenue_estimated", sa.TEXT(), nullable=True),
        sa.Column("funding", sqlite.JSON(), nullable=True),
        sa.Column(
            "technologies_used", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("competitors", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column("hr_maturity", sa.TEXT(), nullable=True),
        sa.Column("recent_news", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
        sa.Column(
            "ai_adoption_signals", sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False
        ),
        sa.Column("why_now_score", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.Column("opportunity_score", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
        sa.ForeignKeyConstraint(["company_id"], ["companies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_research_profiles_company_id"), "research_profiles", ["company_id"], unique=1
    )
    op.drop_index(op.f("ix_email_events_provider_message_id"), table_name="email_events")
    op.drop_index(op.f("ix_email_events_occurred_at"), table_name="email_events")
    op.drop_index(op.f("ix_email_events_event_type"), table_name="email_events")
    op.drop_index(op.f("ix_email_events_delivery_id"), table_name="email_events")
    op.drop_index(op.f("ix_email_events_contact_id"), table_name="email_events")
    op.drop_index(op.f("ix_email_events_campaign_id"), table_name="email_events")
    op.drop_table("email_events")
    op.drop_index(op.f("ix_delivery_events_event_type"), table_name="delivery_events")
    op.drop_index(op.f("ix_delivery_events_delivery_id"), table_name="delivery_events")
    op.drop_table("delivery_events")
    op.drop_index(op.f("ix_delivery_attempts_delivery_id"), table_name="delivery_attempts")
    op.drop_table("delivery_attempts")
    op.drop_index(op.f("ix_decision_history_recipient_lifecycle_id"), table_name="decision_history")
    op.drop_index(op.f("ix_decision_history_execution_status"), table_name="decision_history")
    op.drop_table("decision_history")
    op.drop_index(op.f("ix_campaign_deliveries_run_id"), table_name="campaign_deliveries")
    op.drop_index(
        op.f("ix_campaign_deliveries_provider_message_id"), table_name="campaign_deliveries"
    )
    op.drop_index(op.f("ix_campaign_deliveries_draft_id"), table_name="campaign_deliveries")
    op.drop_table("campaign_deliveries")
    op.drop_index(op.f("ix_recipient_lifecycles_state"), table_name="recipient_lifecycles")
    op.drop_index(
        op.f("ix_recipient_lifecycles_next_evaluation_at"), table_name="recipient_lifecycles"
    )
    op.drop_index(op.f("ix_recipient_lifecycles_contact_id"), table_name="recipient_lifecycles")
    op.drop_index(op.f("ix_recipient_lifecycles_campaign_id"), table_name="recipient_lifecycles")
    op.drop_table("recipient_lifecycles")
    op.drop_index(op.f("ix_recipient_activities_contact_id"), table_name="recipient_activities")
    op.drop_index(op.f("ix_recipient_activities_campaign_id"), table_name="recipient_activities")
    op.drop_table("recipient_activities")
    op.drop_index(
        op.f("ix_sales_intelligence_profiles_company_id"), table_name="sales_intelligence_profiles"
    )
    op.drop_table("sales_intelligence_profiles")
    op.drop_index(op.f("ix_event_audits_event_hash"), table_name="event_audits")
    op.drop_table("event_audits")
    op.drop_index(op.f("ix_campaign_states_state"), table_name="campaign_states")
    op.drop_index(op.f("ix_campaign_states_campaign_id"), table_name="campaign_states")
    op.drop_table("campaign_states")
    op.drop_index(op.f("ix_campaign_runs_campaign_id"), table_name="campaign_runs")
    op.drop_table("campaign_runs")
    op.drop_index(op.f("ix_campaign_metrics_campaign_id"), table_name="campaign_metrics")
    op.drop_table("campaign_metrics")
    op.drop_index(op.f("ix_analytics_snapshots_snapshot_date"), table_name="analytics_snapshots")
    op.drop_index(op.f("ix_analytics_snapshots_campaign_id"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index(op.f("ix_provider_events_provider_name"), table_name="provider_events")
    op.drop_index(op.f("ix_provider_events_processed"), table_name="provider_events")
    op.drop_table("provider_events")
    # ### end Alembic commands ###
