"""SMTP (Gmail/Generic) email provider implementation."""

import email
import imaplib
import smtplib
from email.message import EmailMessage
from typing import Any

from core.services.email.base import BaseEmailProvider
from core.config import get_settings
from core.logger import get_logger

log = get_logger(__name__)
settings = get_settings()

class SMTPProvider(BaseEmailProvider):
    """Email provider using generic SMTP (e.g. Gmail)."""
    
    def __init__(
        self,
        smtp_host: str | None = None,
        smtp_port: int | None = None,
        smtp_user: str | None = None,
        smtp_pass: str | None = None,
        imap_host: str | None = None,
        imap_port: int | None = None,
    ):
        self.smtp_host = smtp_host or getattr(settings, "smtp_host", "smtp.gmail.com")
        self.smtp_port = smtp_port or getattr(settings, "smtp_port", 587)
        self.smtp_user = smtp_user or getattr(settings, "smtp_user", None)
        self.smtp_pass = smtp_pass or getattr(settings, "smtp_pass", None)
        
        self.imap_host = imap_host or getattr(settings, "imap_host", "imap.gmail.com")
        self.imap_port = imap_port or getattr(settings, "imap_port", 993)
            
    async def send_email(
        self,
        to_email: str,
        subject: str,
        body: str,
        reply_to: str | None = None
    ) -> dict[str, Any]:
        """Send an email using SMTP."""
        if not self.smtp_user or not self.smtp_pass:
            log.warning("SMTP credentials not configured.")
            return {"success": False, "message_id": None, "error": "SMTP credentials not configured"}
            
        try:
            msg = EmailMessage()
            msg.set_content(body)
            msg["Subject"] = subject
            msg["From"] = self.smtp_user
            msg["To"] = to_email
            
            if reply_to:
                msg["Reply-To"] = reply_to

            # For Gmail, we use starttls on 587
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_pass)
                server.send_message(msg)
                
            # Message-ID is generated by the EmailMessage or SMTP server
            msg_id = msg.get("Message-ID", "").strip("<>")
            
            return {
                "success": True,
                "message_id": msg_id,
                "error": None
            }
        except Exception as e:
            log.error("Failed to send email via SMTP", error=str(e), to_email=to_email)
            return {
                "success": False,
                "message_id": None,
                "error": str(e)
            }
            
    async def check_replies(self) -> list[dict[str, Any]]:
        """
        Check IMAP inbox for replies to sent emails.
        """
        if not self.smtp_user or not self.smtp_pass:
            log.warning("IMAP credentials not configured (uses SMTP credentials).")
            return []
            
        replies = []
        try:
            # Connect to IMAP
            mail = imaplib.IMAP4_SSL(self.imap_host, self.imap_port)
            mail.login(self.smtp_user, self.smtp_pass)
            mail.select("inbox")
            
            # Search for unseen emails
            status, messages = mail.search(None, "UNSEEN")
            if status == "OK" and messages[0]:
                for num in messages[0].split():
                    typ, msg_data = mail.fetch(num, "(RFC822)")
                    for response_part in msg_data:
                        if isinstance(response_part, tuple):
                            msg = email.message_from_bytes(response_part[1])
                            in_reply_to = msg.get("In-Reply-To", "").strip("<>")
                            if in_reply_to:
                                body = ""
                                if msg.is_multipart():
                                    for part in msg.walk():
                                        if part.get_content_type() == "text/plain":
                                            payload = part.get_payload(decode=True)
                                            if payload:
                                                body += payload.decode()
                                else:
                                    payload = msg.get_payload(decode=True)
                                    if payload:
                                        body = payload.decode()
                                        
                                replies.append({
                                    "thread_id": in_reply_to,
                                    "from_email": msg.get("From"),
                                    "subject": msg.get("Subject"),
                                    "body": body
                                })
            mail.close()
            mail.logout()
        except Exception as e:
            log.error("Failed to check IMAP for replies", error=str(e))
            
        return replies
